
server:
  port: 8090
# 全局配置,默认false,开启后,熔断保护配置方能生效
feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 10
      # 并发执行的最大线程数，默认10
      maxQueueSize: 10
      # BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 10
      # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
      # 首先是检查是否达到coreSize,如果超过,queueSizeRejectionThreshold,仍会拒绝
    hello:
      coreSize: 1
      # 并发执行的最大线程数，默认10
      maxQueueSize: -1
      # BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: -1
      # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
      # 首先是检查是否达到coreSize,如果超过,queueSizeRejectionThreshold,仍会拒绝
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    HelloApi#sayHello(Integer):
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000

